import { NextRequest, NextResponse } from "next/server";

const GEMINI_MODEL = process.env.GEMINI_MODEL || "gemini-3.6-flash";

export async function POST(req: NextRequest) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured in server environment" },
        { status: 500 }
      );
    }

    const body = await req.json();
    const {
      packageTitle = "",
      destination = "",
      selectedHotel = "",
      dayTitle = "",
      dayNumber = 1,
      items = [],
      vibe = "",
    } = body;

    // 1. System Prompt: Australian English, evocative perception-rich guide style, strictly no first person, no prices, no competitors.
    const systemPrompt = `You are an expert Australian travel copywriter creating evocative, perception-rich day descriptions for travel itineraries.

STRICT WRITING RULES:
1. Perspective & Voice: DO NOT use first-person pronouns (NEVER use "I", "me", "my", "we", "our", "us"). Write in an engaging, immersive guidebook style (e.g., "Start in the electric heart of Tokyo, then slow down over a steaming bowl of ramen before watching the city glow from Tokyo Tower."). Focus on atmosphere, sensory details, sights, flavours, and perceptions so the reader can envision the journey.
2. Spelling & Vocabulary: Use Australian English spelling (e.g., colour, favourite, centre, flavour, whilst).
3. Length: Exactly between 150 and 250 words (aim for around 180–220 words in 2 to 3 complete, well-paced paragraphs).
4. Completeness: You MUST bring the narrative to a natural, fully formed conclusion. NEVER leave the final sentence incomplete or cut off mid-thought.
5. No Prices: Do NOT include any monetary amounts, currency symbols, or prices.
6. No Competitor Mentions: Do NOT mention any third-party travel agencies, booking platforms, or competitors.
7. Seamless Narrative: Weave the planned stops and experiences into a flowing, captivating story for this specific day.`;

    // 2. Format user prompt from frontend state
    const activitiesFormatted =
      Array.isArray(items) && items.length > 0
        ? items.map((act: string) => `- ${act}`).join("\n")
        : "- Local exploration and cultural highlights";

    const userPrompt = `Craft an evocative, complete day story based on these itinerary details:
- Trip Title: ${packageTitle || destination || "Travel Experience"}
- Day: Day ${dayNumber} — ${dayTitle || "Daily Highlights"}
- Destination: ${destination || "City Centre"}
- Base / Hotel: ${selectedHotel || "Central accommodation"}
- Atmosphere / Vibe: ${vibe || "Culture, culinary discoveries, and iconic landmarks"}
- Planned Activities & Stops:
${activitiesFormatted}

Write the engaging, complete 150-250 word Australian English narrative with a full concluding sentence now:`;

    // 3. Directly call Gemini REST API
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`;

    const payload = {
      system_instruction: {
        parts: [{ text: systemPrompt }],
      },
      contents: [
        {
          parts: [{ text: userPrompt }],
        },
      ],
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 8192,
      },
    };

    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("[Gemini API Error]", response.status, errorText);
      return NextResponse.json(
        { error: `Gemini API error (${response.status}): ${errorText}` },
        { status: response.status }
      );
    }

    const data = await response.json();
    const candidate = data.candidates?.[0];
    const generatedText = candidate?.content?.parts?.[0]?.text?.trim() || "";

    if (!generatedText) {
      return NextResponse.json(
        { error: "No content generated by Gemini" },
        { status: 502 }
      );
    }

    // 4. Return canonical structure expected by Ticket 1 & 2
    return NextResponse.json({ listing: generatedText });
  } catch (error: any) {
    console.error("[generate-content] Internal error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate content" },
      { status: 500 }
    );
  }
}
